---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - image: ubuntu:18.04
    name: ubuntu-18.04
  - image: ubuntu:16.04
    name: ubuntu-16.04
provisioner:
  name: ansible
verifier:
  name: testinfra
